/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sololopenko (https://sketchfab.com/Sololopenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/target-c9215574514540f294766585fdd62369
Title: Target
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Target =(props)=> {
  const { nodes, materials } = useGLTF('/models/target.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI /2, 0, 15.81]} scale={0.491}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_0.geometry}
          material={materials['Material.001']}
          position={[-10, 8.72, 2.449]}
          rotation={[0, -1, 6]}
          scale={1.45}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/target.glb')
export default Target;